spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wingmarket?characterEncoding=utf8&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: wingmarket
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
    datasource:
      url: jdbc:h2:mem:test;MODE=MYSQL
      driver-class-name: org.h2.Driver
      username: sa


mybatis:
  mapper-locations: mybatis/mapper/**/*.xml
  type-aliases-package: me.wingmarket.entity

logging:
  config: classpath:log4j2.yml

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui-custom.html

