spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL
    driver-class-name: org.h2.Driver
    username: sa



# mapper.xml 위치 지정
mybatis:
  mapper-locations: mybatis/mapper/**/*.xml
  type-aliases-package: me.wingmarket.entity

logging:
  config: classpath:log4j2.yml

springdoc:
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui-custom.html

server:
  port: 8081
